# Generated by Django 5.0.4 on 2024-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=7000)),
                ('servicedate', models.DateField()),
                ('dec', models.TextField(max_length=7000)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='services',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
