# Generated by Django 5.0.4 on 2024-05-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_app', '0002_carservice_remove_appointment_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carservice',
            old_name='servicedate',
            new_name='date',
        ),
    ]
